all:	responseletter_TWwireless.tex
	latex responseletter_TWwireless.tex
	dvips responseletter_TWwireless.dvi -o responseletter_TWwireless.ps
	ps2pdf responseletter_TWwireless.ps



clean:
	rm *.log *.aux *.bbl *.blg *.pdf *.ps *.dvi *.out


cp:
	cp -rf * ~/Dropbox/Ext_CrownCom2015/response\ letter/
