all:	responseletter_TCCN.tex
	latex responseletter_TCCN.tex
	dvips responseletter_TCCN.dvi -o responseletter_TCCN.ps
	ps2pdf responseletter_TCCN.ps



clean:
	rm *.log *.aux *.bbl *.blg responseletter_TCCN.pdf *.ps *.dvi *.out


cp:
	cp -rf * ~/Dropbox/Ext_WCL2015/response\ letter/
